import type { ClaudiusConfigObject } from "../config";
import { generateSandboxHtml } from "./snippet";

/**
 * Open the current config as a StackBlitz project via the documented form-POST
 * API (https://developer.stackblitz.com/platform/api/post-api). No SDK needed.
 */
export function openInStackBlitz(config: ClaudiusConfigObject): void {
  const form = document.createElement("form");
  form.method = "POST";
  form.action = "https://stackblitz.com/run";
  form.target = "_blank";

  const fields: Record<string, string> = {
    "project[title]": "Claudius widget demo",
    "project[description]":
      "Embeddable AI chat widget powered by Claude — generated by the Claudius playground.",
    "project[template]": "html",
    "project[files][index.html]": generateSandboxHtml(config),
  };

  for (const [name, value] of Object.entries(fields)) {
    const input = document.createElement("textarea");
    input.name = name;
    input.value = value;
    form.appendChild(input);
  }

  document.body.appendChild(form);
  form.submit();
  form.remove();
}

/**
 * Open the current config as a CodeSandbox static sandbox via the define API
 * (https://codesandbox.io/docs/learn/sandboxes/cli-api). Returns false when
 * the API call fails so the caller can surface an error.
 */
export async function openInCodeSandbox(
  config: ClaudiusConfigObject,
): Promise<boolean> {
  try {
    const res = await fetch(
      "https://codesandbox.io/api/v1/sandboxes/define?json=1",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          files: {
            "index.html": { content: generateSandboxHtml(config) },
            "package.json": {
              content: JSON.stringify(
                { name: "claudius-widget-demo", version: "0.0.0" },
                null,
                2,
              ),
            },
            "sandbox.config.json": {
              content: JSON.stringify({ template: "static" }, null, 2),
            },
          },
        }),
      },
    );
    if (!res.ok) return false;
    const data = (await res.json()) as { sandbox_id?: string };
    if (!data.sandbox_id) return false;
    window.open(`https://codesandbox.io/s/${data.sandbox_id}`, "_blank");
    return true;
  } catch {
    return false;
  }
}
